---
title: "Reading Data from APIs"
output: github_document
    theme: flatly
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(httr)
library(jsonlite)
library(ggplot2)

```

## Requirements

The packages used in this vignette are 

[tidyverse](https://www.tidyverse.org/)
[httr](https://httr2.r-lib.org/)
[jsonlite](https://cran.r-project.org/package=jsonlite)

## API

## Functions

```{r}

campgrounds <- GET("https://developer.nps.gov/api/v1/campgrounds?limit=1000&api_key=iGcTVkjLRg4ruBc2hld67MDP0XtzaeEygeY0eUlf")

parsed_campgrounds <- fromJSON(rawToChar(campgrounds$content))

activities <- GET("https://developer.nps.gov/api/v1/activities/parks?limit=100&api_key=iGcTVkjLRg4ruBc2hld67MDP0XtzaeEygeY0eUlf")

parsed_activities <- fromJSON(rawToChar(activities$content))

combined_activities <- parsed_activities$data %>%
    enframe()




```


## Exploratory Analysis

```{r}
#EDA Requirements (A few requirements about your EDA are below:
#∗ You should pull data from at least two separate calls to your API functions
#∗ You should create some contingency tables
#∗ You should create numerical summaries for some quantitative variables at each setting of some
#of your categorical variables
#∗ You should create at least five plots utilizing coloring, grouping, etc. All plots should have
#nice labels and titles.
#· At least one plot that you create should be a plot that we didn’t cover in class (say a
#heatmap or something like that - lots of good examples to consider here https://exts.
#ggplot2.tidyverse.org/gallery/))


```

